name: Linux C/C++ CI - Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: gcc 3_Implementation/main.c 3_Implementation/unity/unity.h 3_Implementation/unity/unity.c 3_Implementation/unity/unity_internals.h
